// Copyright 2019 Dmitry Korotych
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//    http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
= Spring Boot Admin Template Application
:encoding: utf-8
:language: bash
:version: 2.5.1

Spring Boot Admin Application for deploy template for Heroku

image:https://www.herokucdn.com/deploy/button.svg[title="Deploy",link="https://heroku.com/deploy/?template=https://github.com/dkorotych/spring-boot-admin-template"]

== Register client
=== Add spring-boot-admin-client dependency

.pom.xml
[source,xml,subs="+verbatim,+attributes"]
----
<dependency>
    <groupId>de.codecentric</groupId>
    <artifactId>spring-boot-admin-client</artifactId>
    <version>{version}</version>
</dependency>
----

or

.build.gradle
[source,groovy,subs="+attributes"]
----
implementation 'de.codecentric:spring-boot-admin-client:{version}'
----


=== Add configuration code look like this to your Spring Boot configuration file
.application.yaml
[source%nowrap,yaml]
----
spring:
  boot:
    admin:
      client:
        url: https://<admin-application-name>.herokuapp.com/
        instance:
          management-base-url: https://<client-application-name>.herokuapp.com/
          service-base-url: ${spring.boot.admin.client.instance.management-base-url}
        auto-deregistration: true
        period: 5m
----

or

.application.properties
[source%nowrap,properties]
----
spring.boot.admin.client.url=https://<admin-application-name>.herokuapp.com/
spring.boot.admin.client.instance.management-base-url=https://<client-application-name>.herokuapp.com/
spring.boot.admin.client.instance.service-base-url=${spring.boot.admin.client.instance.management-base-url}
spring.boot.admin.client.auto-deregistration=true
spring.boot.admin.client.period=5m
----

http://codecentric.github.io/spring-boot-admin/{version}/#client-applications[Additional information] about configuration client application
